# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-05 01:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2017, 1, 5, 9, 33, 7, 843000))),
                ('image', models.TextField(blank=True, max_length=1000, null=True)),
                ('tags', models.TextField(blank=True, max_length=500, null=True)),
                ('article', models.TextField(blank=True, max_length=15000, null=True)),
                ('author', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
